# Generated by assistant
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_alter_user_date_joined_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=124, unique=True, verbose_name="Название навыка"),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, default="", max_length=124, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="surname",
            field=models.CharField(blank=True, default="", max_length=124, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=12, verbose_name="Телефон"),
        ),
    ]
